export const START_QUIZ = "START_QUIZ";
export const FINISH_QUIZ = "FINISH_QUIZ";
export const RESTART_QUIZ = "RESTART_QUIZ";
export const SAVE_ANSWER = "SAVE_ANSWER";

export const STORE_QUESTIONS = "STORE_QUESTIONS";
export const STORE_QUESTION_CATEGORIES = "STORE_QUESTION_CATEGORIES";

